### ISSUE TITLE
Set vm.overcommit_memory=1

### ISSUE THREAD

**Issue by scibi** [debops/ansible-redis#16]
Right now Redis complains that `overcommit_memory` is disabled. Maybe this role should enable it? Without `overcommit_memory` Redis will not be able to fork to perform background save if database is big (more than half of RAM available).

```
Oct  3 10:39:33 some-host redis[694]: WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```

**Comment by drybjed** [comment]
Sure, sounds good. A `sysctl` module task should suffice.
