### ISSUE TITLE
Default init script needs to be diverted

### ISSUE THREAD

**Issue by drybjed** [debops/ansible-redis#2]
During an upgrade, Debian wants to overwrite `/etc/init.d/redis-server` script, which might result in misconfigured service. Default script needs to be diverted to prevent this.

**Comment by ypid** [comment]
This prevents auto updates of Redis. Any progress on this :wink: ?

**Comment by drybjed** [comment]
Oh, yeah. I know how to idempotently divert non-existent files now. Will look into this issue in the evening.

**Comment by ypid** [comment]
I guess this issue is now solved by #13?

**Comment by drybjed** [comment]
Yes, closing.
