### ISSUE TITLE
Consider diverting /etc/redis/redis.conf

### ISSUE THREAD

**Issue by drybjed** [debops/ansible-redis#3]
During an upgrade Debian wants to modify `/etc/redis/redis.conf`. This file is managed by `redis` itself and although we are not templating it, we are modifying it via `lineinfile`. To prevent conflicting modifications by Debian upgrades, we could divert the "original" `/etc/redis/redis.conf` file but also copy it back and modify via `lineinfile` as usual.

**Comment by ypid** [comment]
I guess this issue is now solved by #13?

**Comment by drybjed** [comment]
Yes. Closing.
