### ISSUE TITLE
Problem with empty slaveof

### ISSUE THREAD

**Issue by Seraf** [debops/ansible-redis#5]
Hello,

If sentinel fails to detect the master, an empty slave is filled in redis.conf : 
slaveof 6379

This config makes redis not able to start/restart.

**Comment by drybjed** [comment]
This entry is filled by redis itself, we don't have much control here... Can you provide your Ansible inventory settings related to `debops.redis` role so we could try replicating your environment and see how it behaves?

**Comment by Seraf** [comment]
@drybjed I mean, it's at the end of the file and written by https://github.com/debops/ansible-redis/blob/master/tasks/server.yml#L92 . The check should be done on redis_register_real_master.stdout which can be null if the detect fails (if redis is not reachable for example)

**Comment by drybjed** [comment]
The `debops.redis` role has since been redesigned, the issue should be no longer relevant. @Seraf, do you know if this still happens?

I'm closing this issue for now.
